cask_args appdir: '/Applications'

# GUI
# NOTE: cask only supports macos. linux is not supported. See: https://github.com/Homebrew/discussions/discussions/1081
cask "iterm2"
cask "visual-studio-code" # NOTE: about settings, use https://code.visualstudio.com/docs/editor/settings-sync
cask "docker"
cask "google-chrome"
cask "google-cloud-sdk"
cask "flutter"
cask "android-studio"
tap "dart-lang/dart"
