name: setup macOS

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: macos-10.15
    timeout-minutes: 10
    defaults:
      run:
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
    steps:
      - name: display shell info
        run: echo $ZSH_NAME $ZSH_VERSION

      - run: git clone --depth 1 https://github.com/sensuikan1973/dotfiles.git ~/dotfiles

      - run: ls && ./setup.zsh
        working-directory: ~/dotfiles
