name: Setup macOS

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    runs-on: macos-10.15
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: ./setup.zsh
