name: setup machine

on:
  pull_request:
    paths-ignore:
      - '!.vscode/**/*'
      - '!**.md'
      - '!.github/**/*'
      - '.github/workflows/setup_machine.yaml'
  push:
    branches: [main]
    paths-ignore:
      - '!.vscode/**/*'
      - '!**.md'
      - '!.github/**/*'
      - '.github/workflows/setup_machine.yaml'
  workflow_dispatch:

jobs:
  setup_and_update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: .github/scripts/do_nothing_on_counterpart_workflow.sh
