name: setup macOS

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: macos-10.15
    timeout-minutes: 10
    defaults:
      run:
        shell: zsh {0} # See: https://github.com/actions/virtual-environments/issues/264#issuecomment-574032011
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.HOME }}

      - name: debug
        uses: mxschmitt/action-tmate@v3

      - run: ./setup.zsh
        working-directory: ${{ env.HOME }}/dotfiles
