name: setup linux

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: setup zsh
        run: sudo apt-get install zsh

      - name: display shell info
        shell: zsh {0}
        run: echo $ZSH_NAME $ZSH_VERSION

      - name: checkout repository to HOME
        shell: zsh {0}
        run: |-
          git clone https://github.com/sensuikan1973/dotfiles.git ~/dotfiles
          cd ~/dotfiles
          git fetch origin '+refs/pull/*:refs/remotes/pr/*' # See: https://qiita.com/sonots/items/16df445132e704198e3e
          git checkout $GITHUB_SHA

      # - name: debug
      #   uses: mxschmitt/action-tmate@v3

      # setup twice
      # NOTE: I want to ensure idempotent
      - name: 1st, run setup script
        shell: zsh {0}
        run: cd ~/dotfiles && ./setup.zsh
      - name: 2nd, run setup script
        shell: zsh {0}
        run: cd ~/dotfiles && ./setup.zsh

      - name: rough command test
        shell: zsh {0}
        run: |-
          exec zsh --login
          uname
          la
          cd ~/dotfiles && g status
          crontab -l
